server:
  port: 8091
spring:
  # 配置mysql数据源
  datasource:
    druid:
      username: root
      password: 12345678
      url: jdbc:mysql://127.0.0.1:3306/stock_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initialSize: 6
      # 最小连接池数量
      minIdle: 2
      # 最大连接池数量
      maxActive: 20
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，
      # 并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      maxWait: 60000
  profiles:
    active: cache,stock # 激活其他配置文件，如果有多个文件可以用逗号隔开

#mybatis配置
mybatis:
  # 指定mapper的xml文件的位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hzy.stock.pojo.entity # 批量给实体类起别名，方便xml中直接使用别名，避免冗余配置
  # 开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射sys_user===》SysUser
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #通过mybatis执行的sql语句以日志的形式输出到终端

# 配置分页插件
pagehelper:
  helper-dialect: mysql #配置分页的方言（数据库类型）
  reasonable: true #配置分页合理化参数，如果为true，当pageNum<=0时，会查询第一页，如果为false，则直接根据参数查询超出总共页数范围则查最后一页

